--- 
configurations_1: 
  name: site_name
  value: Flowplace
  configuration_type: string
  description: "The name of the site.  This is used all over the place"
configurations_2:
  name: welcome_text
  value: <h1>Welcome to the Flowplace!</h1>
  configuration_type: text
  description: HTML that shows up on the home-page if no-one is logged in.
configurations_3:
  name: footer
  value: The Flowplace is licensed under the <a href="http://www.gnu.org/licenses/gpl.html">GPL</a>
  configuration_type: text
  description: HTML block for the footer.
configurations_4:
  name: new_user_policy
  value: admin_create
  configuration_type: "options(self_signup,admin_create)"
  description: The site policy on how new users are added to the system
configurations_5: 
  name: global_banner
  value: 
  configuration_type: text
  description: This html text will appear across the top of the site and is dismissable once you log-in.  Used for demo/dev site warinings.
configurations_6: 
  name: analytics
  value: 
  configuration_type: string
  description: Google Analytics html block.
